### PR TITLE
Skip therubyracer/mini_racer dependencies on aarch64 platforms

### PR DESCRIPTION
**Pull request by adam12**
The dependencies that ship libv8 (`therubyracer` and `mini_racer`) are problematic for Apple M1 hardware.

It's easy enough to install nodejs for these platforms on our own, so I think for now it would be best to skip installing when the platform identifies as `aarch64`. This should preserve any existing functionality but allow contributions from Apple M1 hardware (ala me 🤣)

### CODE REVIEW

**Comment by adam12** [comment]
I just noticed that `spec_app` uses `mini_racer` and I wonder if it's better to switch to that instead of removing completely.

**Review by triskweline — APPROVED** [review]

**Comment by triskweline** [comment]
Just FYI: On Ubuntu 20.04 with `node` in the path I could remove both `therubyracer` and `mini_racer` and Unpoly would still build.

**Comment by adam12** [comment]
Good to know. It would be great if we could remove both of these just in general. That was my first implementation, but I didn't want to break your existing setup.

But I'd probably just rather say there's a dependency on `node` being present.

**Comment by triskweline** [comment]
We could remove the dependencies and say in the README that you need to install node to build?

**Comment by adam12** [comment]
> We could remove the dependencies and say in the README that you need to install node to build?

That would be ideal, IMHO.

**Comment by triskweline** [comment]
Alright, I changed it in `master`.

**Pull request merged**
