### PR TITLE
Changed form submit url creation based on button[formactions]

### PR DESCRIPTION
**Pull request by boxxxie**
Buttons with formactions are not respected. `<button formaction="url-string">`

i guess this may also be a problem for `<input type="submit"`
i haven't tested that.

### CODE REVIEW

**Comment by boxxxie** [comment]
I know this isn't the proper way to edit the code (as i'm editing the JS, not coffee).
I'm not really familiar with coffee, but i'll see if i can get the coffee to compile to what i've done in the dist.js code

**Comment by adam12** [comment]
Thank you for the PR. As you noted, Coffeescript is the source of truth which is used to generate the artifacts in `dist/`.

I believe this is fixed in Unpoly 2, if you wanted to save the effort. I'm not sure of a release date for Unpoly 2 but progress is steady so might be reasonably quick. https://github.com/unpoly/unpoly/commit/aec992abb095ebcf65204d813cb2a03a28bba0ab

**Comment by boxxxie** [comment]
@adam12 i was looking through the branches and i couldn't find one for v2. is v2 just master? (if so, then i'm on v2)

**Comment by boxxxie** [comment]
@adam12 i'm trying to build the project, but i'm running into errors with rake.
I haven't done any ruby stuff in the past, so this is a bit hard for me to debug.

```
rake publish:build
rake aborted!
NameError: uninitialized constant Sass::Deprecation
```

would you be able to point me to some resource to help me get my build working?

**Comment by triskweline** [comment]
Thanks for the PR!

As @adam12 said, this is already implemented in Unpoly 2. Version 2 is developed in the `hk/layers` branch and scheduled to be released in the next few weeks.

The [README](https://github.com/unpoly/unpoly/blob/master/README.md) has a list of steps required to make the build. If you're using binaries like `rails` and `rake` make sure to use `bundle exec` (e.g. `bundle exec rake`) so the bundled gem versions are used. If that doesn't help, make sure to use the Ruby version from the README (2.3.8).

**Comment by boxxxie** [comment]
@triskweline i followed the instructions, i run into errors.

i was able to get the coffee script compiling without using rake.

thanks for giving me the branch, i'll use that and see if my problems are solved, if not then i'll see about making a PR to that branch.

**Comment by boxxxie** [comment]
it seems like this problem is fixed for me with the newest commits, however i have found some other errors, i'll make a related issue

**Comment by boxxxie** [comment]
Sorry if this is a bit confusing. but i actually can't confirm if this bug is fixed until i can compile the coffeescript (since dist folder isn't part of the commit log)

work around is making a compiler for button[formaction] and doing up.submit(form, {url: <formaction>}) on click

**Pull request closed without merging**
